---
# handlers file for lamp
- name: start apache
  become: true
  service:
    name: apache2
    state: started

- name: start mariadb
  become: true
  service:
    name: mariadb
    state: started

- name: start httpd
  become: true
  service:
    name: httpd
    state: started
    enabled: true