---
# tasks file for office

- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - libreoffice
      - pidgin
    update_cache: true
    state: present
    cache_valid_time: 600
  tags:
    - packages
    - office