---

- name: Enable CodeReady Builder repository
  become: true
  command: "subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms"
  register: enable_repo_output

# - name: Enable all repos  
#   become: true
#   rhsm_repository:
#     name: "codeready-builder-for-rhel-9-{{ ansible_architecture }}-rpms"
        
#     state: enabled


- name: Install the EPEL repo rpm from a remote repo
  become: true
  ansible.builtin.dnf:
    name: 
      - 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm'
      - 'https://rpms.remirepo.net/enterprise/remi-release-9.rpm'
    state: present
    update_cache: true
    disable_gpg_check: true
    enablerepo: php:remi-8.3
    


